### PR TITLE
Add MIDI Program Change for waveform select and MIDI RT Toggle.

### PR DESCRIPTION
**Pull request by jazamatronic**
Hi,

I wanted a way to change waveforms from my midi controller.
I also wanted a way to ignore RT messages, as I want to select whether I use the zekit seq or my midi seq.

Add MIDI Realtime message toggle using CC 16
    0 = ignore RT messages
  \> 0 = apply RT messages (default)

This builds, although I haven't been able to get it programmed into the PIC yet for testing.  
Please review and comment.

### CODE REVIEW

**Comment by Marzac** [comment]
Dear @jazamatronic, 
and Happy New Year :-)
Basically, I don't accept Github Pull Requests on open-source projects, especially when it is untested code.
There is unfortunately no way I can disable this but I will leave a note on this on the project start page.
The change you are offering is already performed, in a more advanced way, and it will be released in the next version of this firmware.
I wish you a good day.
Frédéric

**Comment by jazamatronic** [comment]
Hello @Marzac ,
Bonne Annee!
Thanks for the update, I'm looking forward to the updated firmware.
When it's released, what will be the best way to update the PIC?
Cheers,
Jared

**Comment by Marzac** [comment]
Dear @jazamatronic,

so I pushed the Firmware 2.0 :-)

You will find the complete changelog here:
https://github.com/Marzac/zekit/blob/main/Firmware/changelog.txt

BTW, your unit is still at my office (the DHL returned it).
Would you like me to update its firmware before shipping?

Best, Frédéric

**Comment by jazamatronic** [comment]
G'day @Marzac,

Wow - I'm impressed, looks great!  

You motivated me to open up zekit, solder in the ISP header and try out my PG164100 - my device is running the v2.0 Firmware and I can stop the midi clocks, cool!  The vibrato sounds cool too.

There must be some mixup with DHL and my unit, I received it sometime near the end of last October, it's been built for a little while now.

Cheers,
Jared

**Comment by jazamatronic** [comment]
P.S. I will now delete my fork, it is no longer useful.

**Comment by Marzac** [comment]
You're just not the same Jared :-)
No worries, my mistake.

**Comment by Marzac** [comment]
Happy you are enjoying this release :-)

I hope you understand why I have a problem with GitHub "pull requests".
There are always things cooking here and I cannot reveal my company planning publicly. This firmware version was almost finished last year but needed extensive testing as music instruments clocking is always something tedious to get right.

For contributing, better contact me ahead in private, it will avoid wasting time and energy on things that are already made or in the pipeline.

Frédéric

**Comment by jazamatronic** [comment]
I have no problem with how you deal with "pull requests", it's your project, and I'm happy to be able to look at the code and poke about a little bit.  I understand your stance.

The only other thing I had in mind was maybe CC glide control, either simple on off or more advanced time control.  I hadn't looked into the code yet, so not even sure that'd be possible, but it was an idea I had floating about.

Cheers,
Jared

**Pull request closed without merging**
